name: 'globant_challenge'
version: '1.0.0'
config-version: 2

profile: 'globant_challenge'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  globant_challenge:
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: analytics
